CREATE TABLE person (
  id   NUMBER(19, 0) PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  age  INTEGER      NOT NULL
);

CREATE SEQUENCE id_sequence
MINVALUE 0
START WITH 10000
INCREMENT BY 1000
CACHE 1;
